---
title: "Result Report: Label Effects on Perceptions and Behaviors Toward Unhoused Individuals"
# If blank, the running header is the title in upper case.
shorttitle: "Label Effects and Homlessness"
# Set names and affiliations.
# It is nice to specify everyone's orcid, if possible.
# There can be only one corresponding author, but declaring one is optional.
author:
  - name: Huidi Yuan
    affiliation: "University of Chicago"
abstract: "This study investigates how inclusive labels, compared to stigmatizing terms, shape public perceptions and prosocial behaviors toward unhoused individuals. Drawing on theories of labeling and stigma, we hypothesized that person-centered labels (e.g., “people experiencing housing insecurity”) would reduce stigma and stereotypes (H1) and increase donations (H2). A preregistered online experiment with 400 U.S. adults tested these hypotheses using a between-subjects design. Participants viewed materials referencing either “the homeless” (stigmatizing label) or “people experiencing housing insecurity” (inclusive label). Results supported H1: PC labels significantly reduced stigma and negative stereotypes. However, H2 was unsupported, as donations did not differ between conditions. Stigma negatively correlated with donation amounts, but stereotypes showed no relationship. Exploratory analyses found no moderation by political orientation or age. These findings highlight the potential of PC labels to mitigate stigma, though additional strategies are needed to bridge the gap between attitudinal and behavioral change. Implications for advocacy, policy communication, and future research are discussed."
# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [Inclusive Language, stigma, homelessness, prosocial behavior, labeling effects]
# Suppress author note
suppress-author-note: true
# If true, tables and figures are mingled with the text instead of listed at the end of the document.
floatsintext: true
# Numbered lines (.pdf and .docx only)
numbered-lines: false
# File with references
bibliography: PC_Label_Homeless_Reference.bib
# Suppress title page
suppress-title-page: false
# Link citations to references
link-citations: true
# If true, adds today's date below author affiliations. If text, can be any value.
# This is not standard APA format, but it is convenient.
# Works with docx, html, and typst. 
draft-date: false
# Language options. See https://quarto.org/docs/authoring/language.html
lang: en
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-typst: 
    keep-typ: true
  apaquarto-pdf:
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    documentmode: man
    keep-tex: true
execute:
  echo: false # set global chunk options: Show output only
  warning: false # override these in individual chunks
---

```{r}
#| label: setup
#| include: false

# Source library R script
source("06_New_Codes/library.R")

```

```{r}
#| label: data-load
#| include: false

# Read data
data_deidentify <- read.csv("data_deidentify.csv")

# Move ppt_ID to the first column
data_deidentify <- data_deidentify %>%
  select(ppt_ID, everything())

view(data_deidentify)
```

```{r}
#| label: cleaning-separate-demo
#| include: false

# Separate demographics
data_demo <- data_deidentify %>%
  select(ppt_ID, 
         label,
         starts_with("Demo_"), 
         comment
         )

write.csv(data_demo, "data_demo.csv", row.names = FALSE)
```

```{r}
#| label: cleaning-separate-fr
#| include: false

# Separate free response questions
data_fr <- data_deidentify %>%
  select(ppt_ID, 
         label,
         general_1,
         general_2,
         like_fr,
         offens_fr,
         impression_1, 
         impression_2,
         impression_3_4_TEXT,
         comment
         )
```

```{r}
#| label: cleaning-separate-quant-main
#| include: false

# Separate columns that is not demo or free response
data_main <- data_deidentify %>%
  select(-c(starts_with("Demo_"),
            general_1,
            general_2,
            like_fr,
            offens_fr,
            impression_1,
            impression_2,
            impression_3_4_TEXT,
            comment)
         ) %>%
  # Correct data type
  mutate(across(where(is.character), # Apply to character columns only
                ~ ifelse(!is.na(suppressWarnings(as.numeric(.))),
                         as.numeric(.), 
                         .))) %>% # If it can be converted to numeric, convert it
  # Correct data type for columns with NA
  mutate(
    experience_1 = as.numeric(experience_1),
    experience_2 = as.numeric(experience_2),
    experience_3 = as.numeric(experience_3),
    SliderOverlapValue = as.numeric(SliderOverlapValue)
  ) %>%
  # Select rows that pass attention check
  filter(check == 2)
  
```

# Result