---
title: "PC_Pilot_1"
output:
  pdf_document: default
  html_document: default
date: "2024-11-18"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cleaning

```{r}
library(readr)
library(tidyverse)
library(ggplot2)

data <- read_csv("PC_Pilot-English_November 19, 2024_10.12.csv")
View(data)

data_header_rm <- data[-c(1,2),] #remove qualtrics duplicate headers
data_header_rm[data_header_rm == ""] <- NA #empty string = NA
View(data_header_rm)

# Prolific, pass consent, and prescreen
data_passed <- data_header_rm %>%
  filter(
    Finished == 1,
    consent == 1,
    str_length(ID) == 24, # Prolific IDs
  )

#rows with fraud
data_fraud <- data_passed %>%
  filter(
    Q_BallotBoxStuffing == "True",
    Q_RecaptchaScore <= 0.5,
    Q_RelevantIDDuplicate == "True",
    Q_RelevantIDDuplicateScore >= 75,
    Q_RelevantIDFraudScore >= 30
  )

#remove unnecessary columns
data_passed1 <- data_passed %>%
  filter(!PROLIFIC_PID %in% data_fraud$PROLIFIC_PID) %>% #remove fraud
  select(-c(StartDate,
            EndDate,
            Status,
           IPAddress,
           Progress,
           Finished,
           RecordedDate,
           ResponseId,
           RecipientLastName,
           RecipientFirstName,
           RecipientEmail,
           ExternalReference,
           LocationLatitude,
           LocationLongitude,
           DistributionChannel,
           UserLanguage,
           'Duration (in seconds)',
           Q_BallotBoxStuffing,
           Q_RecaptchaScore,
           Q_RelevantIDDuplicate,
           Q_RelevantIDDuplicateScore,
           Q_RelevantIDFraudScore,
           PROLIFIC_PID,
           consent, 
           not_pc_label, 
           pc_label
           )) %>%
  mutate(ppt_ID = row_number())
```

```{r}
# Separate demographics
data_demo <- data_passed1 %>%
  select(ppt_ID, ID,
         label,
         starts_with("Demo_"), 
         comment
         )

write.csv(data_demo, "demo_11082024.csv", row.names = FALSE)

# Main data
data_main <- data_passed1 %>%
  select(-c(ID, # de-identified
            starts_with("Demo_"), 
            comment)) %>%
  mutate(across(where(is.character), # Apply to character columns only
                ~ ifelse(!is.na(suppressWarnings(as.numeric(.))),
                         as.numeric(.), 
                         .)))

```

## Analysis - Simple

```{r}
# Overlap compare
data_main %>%
  group_by(label) %>%
  summarise(overlap_avg = mean(SliderOverlapValue))

# Stigma: PC vs. PIC

## recode stigma_resp_2, stigma_dist_2, stigma_dist_3
data_main_recode <- data_main %>%
  mutate(stigma_resp_2_mut = 6 - stigma_resp_2,
         stigma_dist_2_mut = 6 - stigma_dist_2, 
         stigma_dist_3_mut = 6 - stigma_dist_3) %>%
  select(-c(stigma_resp_2, stigma_dist_2, stigma_dist_3))

## average stigma 
data_main_recode %>%
  mutate(stigma_avg_ppt = rowSums(select(., starts_with('stigma_')))/6) %>% 
  group_by(label) %>%
  summarise(stigma_avg_label = mean(stigma_avg_ppt))
  
## stigma_resp
data_main_recode %>%
  mutate(stigma_resp_ppt = rowSums(select(., starts_with('stigma_resp')))/2) %>% 
  group_by(label) %>%
  summarise(stigma_resp_label = mean(stigma_resp_ppt))

## stigma_dist
data_main_recode %>%
  mutate(stigma_dist_ppt = rowSums(select(., starts_with('stigma_dist')))/3) %>% 
  group_by(label) %>%
  summarise(stigma_dist_label = mean(stigma_dist_ppt))

## stigma_danger
data_main_recode %>%
  group_by(label) %>%
  summarise(stigma_danger_label = mean(stigma_danger))


# Stereotype: PC vs. PIC

## average stertyp
data_main %>%
  mutate(stertyp_avg_ppt = rowSums(select(., starts_with('stertyp_')))/8) %>% 
  group_by(label) %>%
  summarise(stertyp_avg_label = mean(stertyp_avg_ppt))

## stertyp_cmptition
data_main %>%
  mutate(stertyp_cmptition_ppt = rowSums(select(., starts_with('stertyp_cmptition_')))/2) %>% 
  group_by(label) %>%
  summarise(stertyp_cmptition_label = mean(stertyp_cmptition_ppt))

## stertyp_comp
data_main %>%
  mutate(stertyp_comp_ppt = rowSums(select(., starts_with('stertyp_comp_')))/2) %>% 
  group_by(label) %>%
  summarise(stertyp_comp_label = mean(stertyp_comp_ppt))

## stertyp_warm
data_main %>%
  mutate(stertyp_warm_ppt = rowSums(select(., starts_with('stertyp_warm_')))/2) %>% 
  group_by(label) %>%
  summarise(stertyp_warm_label = mean(stertyp_warm_ppt))

## stertyp_status
data_main %>%
  mutate(stertyp_status_ppt = rowSums(select(., starts_with('stertyp_status_')))/2) %>% 
  group_by(label) %>%
  summarise(stertyp_status_label = mean(stertyp_status_ppt))


# Average donation: PC vs. PIC
data_main %>%
  group_by(label) %>%
  summarise(donate_homeless_label = mean(donate_1))

# concept_1, concept_2, concept_3 
data_main %>%
  group_by(label) %>%
  summarise(concept_shelter_lable = mean(concept_1))

data_main %>%
  group_by(label) %>%
  summarise(concept_unemploy_lable = mean(concept_2))

data_main %>%
  group_by(label) %>%
  summarise(concept_duration_lable = mean(concept_3))


# Average like, offens: if distinct from 1.5 
data_main %>%
  summarise(like_avg_ppt = mean(like), 
            offense_avg_ppt = mean(offens))

## like, offens: if correlated with label
data_main %>%
  group_by(label) %>%
  summarise(like_avg_label = mean(like), 
            offense_avg_label = mean(offens))

# Distribution of impression_2
data_main %>%
  summarise(impression_2_avg = mean(impression_2))

data_main$impression_2 <- factor(data_main$impression_2, 
                            levels = c(1, 2, 3, 4), 
                            labels = c("PIC", "PC", "Both", "Neither"))

ggplot(data_main, aes(x = impression_2)) +
  geom_bar() +
  labs(title = "Distribution of Impression_2", 
       x = "Impression_2", 
       y = "Frequency") +
  theme_minimal()
```
